version: '3.0'

services:
  haxall:
    image: "needleinajaystack/haxall:latest"
    environment:
      - SU_USER=su
      - SU_PASS=su
    ports:
      - 8080:8080/tcp
    volumes:
      - haxall:/opt/haxall/proj
  grafana:
    image: "grafana/grafana-oss:latest"
    environment:
      - GF_DEFAULT_APP_MODE=development
    ports:
      - 3000:3000/tcp
    volumes:
      - grafana:/var/lib/grafana
      - ./plugins:/var/lib/grafana/plugins
volumes:
  haxall:
  grafana:
